name: Update CSV

on:
  schedule:
    - cron: '0 9 * * *'  # Menjalankan aliran kerja setiap hari pada pukul 00:00 UTC

jobs:
  update_csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Update CSV from Google Drive
        run: |
          # Add commands here to fetch and update the CSV from Google Drive
          # Example: curl or wget commands
          
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update CSV from Google Drive"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
