name: Update Data

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 9 * * *' # Menjalankan alur kerja setiap hari jam 7 pagi

jobs:
  update_data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download CSV from Google Drive
        run: |
          # Script untuk mengunduh file CSV dari Google Drive
          # Ganti dengan script atau perintah yang sesuai untuk mengunduh file

      - name: Update CSV in Repository
        run: |
          # Script untuk memperbarui file CSV di repositori GitHub
          # Ganti dengan script atau perintah yang sesuai untuk memperbarui file
          
      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update CSV"
          git push
